// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElBacktop: typeof import('element-plus/es')['ElBacktop']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
}
export {}
