// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/articleCard/src/articleCard.vue')['default']
    ClassifyCard: typeof import('./src/components/classifyCard/src/classifyCard.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    InfoCard: typeof import('./src/components/infoCard/src/InfoCard.vue')['default']
    LoadingBox: typeof import('./src/components/loadingBox/src/loadingBox.vue')['default']
    Markdown: typeof import('./src/components/markdown/src/markdown.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/navHeader.vue')['default']
    WebsiteInfoCard: typeof import('./src/components/websiteInfoCard/src/websiteInfoCard.vue')['default']
  }
}

export { }
